# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd" "i2c-dev" "i2c-piix4" "wireguard"];
    extraModulePackages = [];
    kernel.sysctl = {"vm.max_map_count" = 16777216;};
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/697cf76c-8c44-4eda-881e-d5875c5ee947";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/697cf76c-8c44-4eda-881e-d5875c5ee947";
    fsType = "btrfs";
    options = ["subvol=home/@home"];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/6A96-5897";
    fsType = "vfat";
  };

  fileSystems."/boot" = {
    device = "/efi";
    fsType = "none";
    options = ["bind"];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/9d4c7818-0978-4d86-9bfb-3f945799fec2";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.xserver.videoDrivers = ["nvidia"];
  hardware.opengl.driSupport32Bit = true;
  hardware.nvidia.modesetting.enable = true;

  services.hardware.openrgb = {
    enable = true;
    motherboard = "amd";
  };
}
